name: Build and Run with Intel ICX

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-run-icx:
    runs-on: windows-latest

    steps:
      # Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # Cache the Intel installer
      - name: Cache Intel OneAPI installer
        id: cache-oneapi
        uses: actions/cache@v4
        with:
          path: intel-oneapi-base-toolkit-2025.2.1.46.exe
          key: oneapi-installer-v1

      # Download the installer only if not cached
      - name: Download Intel OneAPI web installer
        if: steps.cache-oneapi.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          Write-Host "Downloading Intel oneAPI web installer..."
          Invoke-WebRequest -Uri "https://github.com/KartikayKaul/Matrix/releases/download/v1.0/intel-oneapi-base-toolkit-2025.2.1.46.exe" -OutFile "intel-oneapi-base-toolkit-2025.2.1.46.exe"
          Write-Host "Download complete."

      # Install Intel oneAPI (silent mode)
      - name: Install Intel oneAPI Base Toolkit
        shell: pwsh
        run: |
          Write-Host "Installing Intel oneAPI Base Toolkit silently..."
          Start-Process -FilePath ".\intel-oneapi-base-toolkit-2025.2.1.46.exe" -ArgumentList "-a", "--silent", "--eula", "accept" -Wait
          Write-Host "Intel oneAPI installation complete."

      # Build with icx (no OpenMP yet)
      - name: Build main.cpp with Intel ICX
        shell: pwsh
        run: |
          & "C:\\Program Files (x86)\\Intel\\oneAPI\\compiler\\latest\\windows\\bin\\icx.exe" /EHsc /O3 /std:c++17 /arch:AVX main.cpp -o main_icx.exe

      # Run the executable
      - name: Run Intel-compiled binary
        shell: pwsh
        run: |
          Write-Host "Running Intel-compiled binary..."
          ./main_icx.exe 1024
