name: Build and Run with Intel ICX

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-run-icx:
    runs-on: windows-latest

    steps:
      #  Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      #  Setup Intel oneAPI (Intel C++ compiler)
      - name: Setup Intel oneAPI
        uses: intel/oneapi-setup-action@v1
        with:
          components: 'compiler'

      #  Build with icx
      - name: Build main.cpp with icx
        shell: pwsh
        run: |
          icx /EHsc /O3 /std:c++17 /Qiopenmp /arch:AVX main.cpp -o main_icx.exe

      #  Run the executable
      - name: Run main_icx.exe
        shell: pwsh
        run: |
          ./main_icx.exe 1024
