name: Build and Run with Intel oneAPI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-run-icx:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Download Intel oneAPI Web Installer (from your release)
      - name: Download Intel oneAPI Web Installer
        shell: pwsh
        run: |
          Write-Host "Downloading Intel oneAPI installer from GitHub release..."
          Invoke-WebRequest -Uri "https://github.com/KartikayKaul/Matrix/releases/download/v1.0/intel-oneapi-base-toolkit-2025.2.1.46.exe" -OutFile "intel_oneapi_installer.exe"

      # 3️⃣ Install oneAPI Base Toolkit silently
      - name: Install Intel oneAPI Base Toolkit
        shell: pwsh
        run: |
          Write-Host "Installing Intel oneAPI Base Toolkit (silent mode)..."
          Start-Process -FilePath ".\intel_oneapi_installer.exe" -ArgumentList "-a", "--silent", "--eula", "accept", "-p=NEED_VS2022_INTEGRATION=0" -Wait
          Write-Host "Intel oneAPI installation complete."

      # 4️⃣ Load Intel compiler environment
      - name: Set up Intel compiler environment
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
          icx /QV

      # 5️⃣ Build your C++ program
      - name: Build main.cpp with Intel ICX
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Intel\oneAPI\setvars.bat"
          icx /EHsc /O3 /std:c++17 /arch:AVX main.cpp -o main_icx.exe

      # 6️⃣ Run the built executable
      - name: Run main_icx.exe
        shell: pwsh
        run: |
          Write-Host "Running Intel-compiled binary..."
          ./main_icx.exe 1024
