name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build examples.cpp with FMA and OpenMP
      run: g++ -std=c++17 -mfma -fopenmp -o examples Examples/examples.cpp

    - name: Build examples.cpp with FMA, OpenMP as well as O3 optimization
      run: g++ -std=c++17 -mfma -fopenmp -O3 -o examples2 Examples/examples.cpp
    - name: Run examples1
      run: ./examples 1024
    - name: Run examples2
      run: ./examples2 128
    
    - name: Build main.cpp with FMA, OpenMP as well as O3 optimization
      run: g++ -std=c++17 -mfma -fopenmp -O3 -o main main.cpp
    - name: Run main executable with size 128
      run: ./main 128
    - name: Run main executable with size 256
      run: ./main 256
    - name: Run main executable with size 512
      run: ./main 512
    
      
