name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up C++ compiler
      uses: actions/setup-cpp@v2
      with:
        compiler: gcc

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Build examples.cpp
      run: |
        g++ -std=c++11 -o examples Examples/examples.cpp

    - name: Run examples
      run: ./Examples
